In [1]:
import numpy as np
d3=np.arange(50).reshape(2,5,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [2]:
d3[1]


array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [3]:
d3[0,2,1:4]

array([11, 12, 13])

In [4]:
d3[0:,2:4,1:3]

array([[[11, 12],
        [16, 17]],

       [[36, 37],
        [41, 42]]])

In [5]:
d3[1,0:,3:4]
d3[0:,0:,3:4]



array([[[ 3],
        [ 8],
        [13],
        [18],
        [23]],

       [[28],
        [33],
        [38],
        [43],
        [48]]])

# Broadcasting

In [6]:


x=np.array([[1,2,3]])
y=np.array([[1],[2],[3]])
x.shape,y.shape



((1, 3), (3, 1))

In [7]:
x,y=np.broadcast_arrays(x,y)
print(x,',',y)

x+y

[[1 2 3]
 [1 2 3]
 [1 2 3]] , [[1 1 1]
 [2 2 2]
 [3 3 3]]


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Pandas

In [8]:
#Pandas Data Structre
#Series Data Frame



In [9]:
import pandas as pd
ss=pd.Series([1111,2222,3333,4444,5555])
ss

0    1111
1    2222
2    3333
3    4444
4    5555
dtype: int64

In [10]:
ss[[1,3,2,0]]

1    2222
3    4444
2    3333
0    1111
dtype: int64

In [11]:
ss[3]=5566
ss

0    1111
1    2222
2    3333
3    5566
4    5555
dtype: int64

In [12]:
ss[[3,1,0]]=5555,77777,99999
ss
ss
#delete Single Value
#del ss[2]
#multiple insert or delete not allowed


0    99999
1    77777
2     3333
3     5555
4     5555
dtype: int64

In [13]:
sl=pd.Series([10,20,30,40,50],index=[11,"aa","bb",33,"cc"])
sl

11    10
aa    20
bb    30
33    40
cc    50
dtype: int64

In [14]:
adic={"name":"aaa","ag":"12","cl":"kk"}
adic

{'name': 'aaa', 'ag': '12', 'cl': 'kk'}

In [15]:
sg=pd.Series(adic)
sg

name    aaa
ag       12
cl       kk
dtype: object

In [16]:
sn=pd.Series(sg,index=["ag","cl","ny"])
sn

ag     12
cl     kk
ny    NaN
dtype: object

In [17]:
sn.index

Index(['ag', 'cl', 'ny'], dtype='object')

In [18]:
sn.values

array(['12', 'kk', nan], dtype=object)

In [19]:
sn.index

Index(['ag', 'cl', 'ny'], dtype='object')

In [20]:
'ag' in sn

True

In [21]:
pd.isnull(sn)

ag    False
cl    False
ny     True
dtype: bool

In [22]:
pd.isna(sn)

ag    False
cl    False
ny     True
dtype: bool

# data Frame

In [23]:
df=pd.DataFrame([123,345,678])
df

0
0  123
1  345
2  678

In [32]:
df=pd.DataFrame(["Red","Blue","Green"],index=["v1","v2","v3"])
df

0
v1    Red
v2   Blue
v3  Green

In [33]:
df1=pd.DataFrame(["Red","Blue","Green"],index=["v1","v2","v3"],columns=["Color"])
df1

Color
v1    Red
v2   Blue
v3  Green

# Creating a Data Frame From Dictionary

In [34]:
score={"Course1":[76,78,89,90,83,82,87,89,90,93],
       "Course2":[67,78,76,75,89,90,54,78,87,45],
       "Course3":[78,76,79,56,34,89,45,78,91,89]   
}
df=pd.DataFrame(score,index=["student1","student2","student3","student4","student5","student6","student7","student8","student9","student10"])
df



Course1  Course2  Course3
student1        76       67       78
student2        78       78       76
student3        89       76       79
student4        90       75       56
student5        83       89       34
student6        82       90       89
student7        87       54       45
student8        89       78       78
student9        90       87       91
student10       93       45       89

In [27]:
#for read Data fom File
#df=pd.read_csv("filename")

In [35]:
score={"Course1":[76,78,89,90,83,82,87,89,90,93],
       "Course2":[67,78,76,75,89,90,54,78,87,45],
       "Course3":[78,76,79,56,34,89,45,78,91,89]   
}
df=pd.DataFrame(score,index=["Student1","Student2","Student3","Student4","Student5","Student6","Student7","Student8","Student9","Student10"])
df


Course1  Course2  Course3
Student1        76       67       78
Student2        78       78       76
Student3        89       76       79
Student4        90       75       56
Student5        83       89       34
Student6        82       90       89
Student7        87       54       45
Student8        89       78       78
Student9        90       87       91
Student10       93       45       89

In [36]:
#df.head()  first five
#df.tail()  last  five
#df.info()   #give info of data
#df.describe()  #give descripton of data

#print(df.Course1)
#df["Course1"]

df[["Course1","Course2"]]



Course1  Course2
Student1        76       67
Student2        78       78
Student3        89       76
Student4        90       75
Student5        83       89
Student6        82       90
Student7        87       54
Student8        89       78
Student9        90       87
Student10       93       45

In [37]:

df.loc[["Student7","Student6"]]  # for Specic row

#df.loc[["Student7","Student6"]]['Course3']  # for Specic row


Course1  Course2  Course3
Student7       87       54       45
Student6       82       90       89

In [38]:
df

df['Total Marks']=df['Course1']+df['Course2']+df['Course3']
df['Percentage %']=round( df['Total Marks']/300*100)
df


#df['Grade']=np.where(df['Total Marks']<200,"Fail","Pass")
df['Grade']=np.where((df['Course1']>=50) & ( df['Course2']>=50) & ( df['Course3']>=50)  ,"Pass","Fail")
df



Course1  Course2  Course3  Total Marks  Percentage % Grade
Student1        76       67       78          221          74.0  Pass
Student2        78       78       76          232          77.0  Pass
Student3        89       76       79          244          81.0  Pass
Student4        90       75       56          221          74.0  Pass
Student5        83       89       34          206          69.0  Fail
Student6        82       90       89          261          87.0  Pass
Student7        87       54       45          186          62.0  Fail
Student8        89       78       78          245          82.0  Pass
Student9        90       87       91          268          89.0  Pass
Student10       93       45       89          227          76.0  Fail