In [96]:

%config IPCompleter.greedy=True
##Numpy
##Arrays and Vectorized Computation

import numpy as np
'''
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
'''
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) 




(2, 3)
1 2 4


In [95]:
import numpy as np

'''
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(3)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
                      
 #shape(a,b,c)
 a=matrices
 b=Rows
 c=Columns
        
'''

e = np.random.random((2,4,2))  # Create an array filled with random values
print(e)
f=np.random.randn(2,2)
f

[[[0.99069807 0.37777168]
  [0.1880609  0.17843212]
  [0.76686475 0.93013913]
  [0.80153462 0.52148891]]

 [[0.75559816 0.55129021]
  [0.22315163 0.66837049]
  [0.22156375 0.79749612]
  [0.96838632 0.33512004]]]


array([[-1.34474313,  1.52169413],
       [-0.24000739,  1.12692343]])

In [72]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]]])
b=a*2
print(b.shape)
print(b.ndim)
h=np.arange(64).reshape(4,4,4)
h

(1, 2, 3)
3


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [89]:
'''
#shape(a,b,c)
 a=matrices
 b=Rows
 c=Columns
'''

k=np.arange(30).reshape(3,5,2)
#print(k)
k.ndim

#k+k
j=np.random.random((3,5,2))
print(j)
j*k
print(j.shape)
print(k.shape)

[[[0.86224325 0.75488958]
  [0.21835198 0.20540781]
  [0.74050175 0.41398403]
  [0.34414269 0.5413198 ]
  [0.97128217 0.32132918]]

 [[0.29065938 0.6764617 ]
  [0.83926267 0.88564942]
  [0.37812595 0.89693214]
  [0.56689962 0.79775682]
  [0.28383414 0.45053692]]

 [[0.0572741  0.55432004]
  [0.71812701 0.19412302]
  [0.96901469 0.62753769]
  [0.52446698 0.13183157]
  [0.22557106 0.4110759 ]]]
(3, 5, 2)
(3, 5, 2)


In [105]:

%config IPCompleter.greedy=True
a=np.array([[[1,2,3],[4,5,6]]])

print(a)


np.zeros((3,4))

[[[1 2 3]
  [4 5 6]]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
np.empty(6)
np.ones((2,2))*5


array([[5., 5.],
       [5., 5.]])